spring:
  application:
    name: splash-task
  datasource:
    url: jdbc:postgresql://zimaos.local:5432/casaos
    username: casaos
    password: casaos
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
